services:
  neo4j:
    image: neo4j:${NEO4J_VERSION:-5.26.2}
    restart: ${RESTART_POLICY:-always}
    healthcheck:
      test: wget "http://localhost:7474" || exit 1
      interval: 5s
      timeout: 90s
      retries: 90
      start_period: 90s
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - graphiti_neo4j_data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-zepzepzep}

  graph:
    build:
      context: .
      dockerfile: ${GRAPHITI_DOCKERFILE:-Dockerfile}
    restart: ${RESTART_POLICY:-always}
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 10s
      timeout: 90s
      retries: 5
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-zepzepzep}
      PORT: 8000
      MODEL_NAME: ${MODEL_NAME:-gpt-4o-mini}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-text-embedding-3-small}
    ports:
      - "8484:8000"

volumes:
  graphiti_neo4j_data:
